### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by murilotimo** [tunele/moodle-profilefield_dynamicmultiselect#2]
Hello,

I installed the dynamicmultiselect plugin
And moodle in the version Moodle 3.1.2+ (Build: 20160915)

I'm using the following query: Select id, fullname as data from {course}

When I try to add a resource in a any course the following error appears:

Debug info: 

[array (
)]
Error code: dmlreadexception
×Stack trace:
line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 794 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 62 of /user/profile/field/dynamicmultiselect/field.class.php: call to pgsql_native_moodle_database->get_records_sql()
line 612 of /user/profile/lib.php: call to profile_field_dynamicmultiselect->__construct()
line 340 of /availability/condition/profile/classes/condition.php: call to profile_get_custom_fields()
line 70 of /availability/condition/profile/classes/frontend.php: call to availability_profile\condition::get_custom_profile_fields()
line 129 of /availability/classes/frontend.php: call to availability_profile\frontend->get_javascript_init_params()
line 619 of /course/moodleform_mod.php: call to core_availability\frontend::include_all_javascript()
line 39 of /mod/label/mod_form.php: call to moodleform_mod->standard_coursemodule_elements()
line 201 of /lib/formslib.php: call to mod_label_mod_form->definition()
line 95 of /course/moodleform_mod.php: call to moodleform->__construct()
line 255 of /course/modedit.php: call to moodleform_mod->__construct()
×Output buffer: <br /> <b>Notice</b>: Trying to get property of non-object in <b>/srv/www/moodle31/user/profile/field/dynamicmultiselect/field.class.php</b> on line <b>60</b><br />

Can you help us?

**Comment by nadavkav** [comment]
I got the same issue (trying to add a new Quiz instance to a course)
The solution was in Moodle's core:
https://github.com/moodle/moodle/blob/master/user/profile/lib.php#L658
Change:
```
$formfield = new $newfield();
```
To:
```
$formfield = new $newfield($field->id);
```
As without knowing the original field id, it can not pass (or use) the SQL query and other properties to the newly created dynamicmultiselect field.

**Comment by tunele** [comment]
fixed
